# Generated by Django 2.2 on 2019-02-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('pageNumber', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=30)),
                ('publishDate', models.DateField()),
            ],
        ),
    ]
